# Step 1: Build the Go application
FROM golang:1.21.12-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code to the container
COPY . .

# Build the Go app
RUN go build -o main ./cmd

# Step 2: Create a small image for running the application
FROM alpine:latest

WORKDIR /root/

# Install tzdata to handle timezones
RUN apk add --no-cache tzdata

# Set the timezone to Asia/Jakarta
ENV TZ=Asia/Jakarta

# Copy the prebuilt binary from builder image
COPY --from=builder /app/main .
COPY --from=builder /app/cmd/config.env .

# Expose the port the app runs on
EXPOSE 9001

# Command to run the binary
CMD ["./main"]