package constants

const (
	SPEED_HAULER_COLOR_OVER   = "#FFBEBE"
	SPEED_HAULER_COLOR_UNDER  = "#FFE03D"
	SPEED_HAULER_COLOR_NORMAL = "#C2FFC5"
	SPEED_HAULER_VALUE_OVER   = 25.01
	SPEED_HAULER_VALUE_UNDER  = 20.0
	SPEED_HAULER_EMPTY_OVER   = 23.42
	SPEED_HAULER_EMPTY_UNDER  = 23.42
	SPEED_HAULER_LOADED_OVER  = 22.38
	SPEED_HAULER_LOADED_UNDER = 22.38
)
