package constants

const (
	STATUS_DATA_INSERT  = "I"
	STATUS_DATA_INSERT2 = "I2"

	STATUS_DATA_UPDATE  = "U"
	STATUS_DATA_UPDATE1 = "U1"
	STATUS_DATA_UPDATE2 = "U2"
	STATUS_DATA_UPDATE3 = "U3"

	STATUS_DATA_DELETE = "D"
)
