// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mintegra/login": {
            "post": {
                "description": "Create Authenticate user, store in redis, and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Login With Redis",
                "parameters": [
                    {
                        "description": "Login Post Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.LoginMainResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    }
                }
            }
        },
        "/mintegra/notification/post": {
            "post": {
                "description": "Send POST Notification to WebSocket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "POST Notification",
                "parameters": [
                    {
                        "description": "Data POST Notification",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_notification.NotificationMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST Notification sent!",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to send notification",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/mintegra/notification/pub": {
            "get": {
                "description": "Get Publish Notification",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "Publish Notification WebSocket",
                "responses": {
                    "101": {
                        "description": "WebSocket connection established",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_notification.NotificationMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    }
                }
            }
        },
        "/mintegra/notification/sos": {
            "post": {
                "description": "Send SOS Notification to WebSocket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "SOS Notification",
                "parameters": [
                    {
                        "description": "Data SOS Notification",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_notification.NotificationMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SOS Notification sent!",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to send notification",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/mintegra/notification/sub": {
            "get": {
                "description": "Get Subscribe Notification",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "Subscribe to Notification WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel format. Contoh nilai yang valid:\n1. customer_no:site:master-data\n2. customer_no:site:opr-dispatch\n3. customer_no:site:opr-report\n4. customer_no:site:opr-fleet\n5. customer_no:site:plant-oem\n6. customer_no:site:all",
                        "name": "channel",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket connection established",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_notification.NotificationMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    }
                }
            }
        },
        "/mintegra/notification/test": {
            "post": {
                "description": "Test Notification to WebSocket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "Test Notification",
                "parameters": [
                    {
                        "description": "Data Test Notification",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_notification.NotificationMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notification sent!",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to send notification",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/session-data": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Session Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Get Session Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.SessionDataMainResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of User by filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master User"
                ],
                "summary": "Get Master User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer No",
                        "name": "customer_no",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Site",
                        "name": "site",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Department",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Section",
                        "name": "section",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Position",
                        "name": "position",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Crew",
                        "name": "crew",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Phone Number",
                        "name": "phone_no",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status Data",
                        "name": "status_data",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Source",
                        "name": "source",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "\"2006-01-02 15:04:05\"",
                        "description": "Last Update Time",
                        "name": "last_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.TUserMainResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create one or more master User entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master User"
                ],
                "summary": "Create Master User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer No",
                        "name": "customer_no",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User Post Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_request.TUserPostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.MainResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_royanqodri_Login-Gateway-API_model_notification.NotificationMessage": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "string"
                },
                "altitude": {
                    "type": "number"
                },
                "bearing": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "channel": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "customer_no": {
                    "type": "string"
                },
                "date_log": {
                    "type": "string"
                },
                "equipment_model": {
                    "type": "string"
                },
                "equipment_no": {
                    "type": "string"
                },
                "equipment_type": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "fleet": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "shift": {
                    "type": "string"
                },
                "shift_sequence": {
                    "type": "integer"
                },
                "site": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "status_activity": {
                    "type": "string"
                },
                "time_log": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_request.LoginRequest": {
            "type": "object",
            "required": [
                "menu",
                "password",
                "username"
            ],
            "properties": {
                "menu": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "site": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_request.TUserPostDetailRequest": {
            "type": "object",
            "required": [
                "blood_type",
                "email_address",
                "id_customer",
                "name",
                "password",
                "phone_no",
                "type",
                "username"
            ],
            "properties": {
                "blood_type": {
                    "type": "string"
                },
                "email_address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_customer": {
                    "type": "integer"
                },
                "insert_by": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_no": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "update_by": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_request.TUserPostRequest": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_request.TUserPostDetailRequest"
                    }
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.LoginMainResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.LoginResponse"
                    }
                },
                "data_header": {},
                "status_response": {
                    "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.StatusResponse"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.LoginResponse": {
            "type": "object",
            "properties": {
                "customer_no": {
                    "type": "string"
                },
                "id_customer": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.MainResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "data_header": {},
                "status_response": {
                    "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.StatusResponse"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.SessionDataMainResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.SessionDataResponse"
                    }
                },
                "data_header": {},
                "status_response": {
                    "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.StatusResponse"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.SessionDataResponse": {
            "type": "object",
            "properties": {
                "blood_type": {
                    "type": "string"
                },
                "customer_no": {
                    "type": "string"
                },
                "data_modules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.TUserModuleResponse"
                    }
                },
                "email_address": {
                    "type": "string"
                },
                "id_customer": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone_no": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.StatusResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "status_text": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.TUserGetResponse": {
            "type": "object",
            "properties": {
                "blood_type": {
                    "type": "string"
                },
                "customer_no": {
                    "type": "string"
                },
                "email_address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_customer": {
                    "type": "integer"
                },
                "insert_by": {
                    "type": "string"
                },
                "insert_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_no": {
                    "type": "string"
                },
                "status_data": {
                    "type": "string"
                },
                "update_by": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.TUserMainResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.TUserGetResponse"
                    }
                },
                "data_header": {},
                "status_response": {
                    "$ref": "#/definitions/github_com_royanqodri_Login-Gateway-API_model_response.StatusResponse"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "github_com_royanqodri_Login-Gateway-API_model_response.TUserModuleResponse": {
            "type": "object",
            "properties": {
                "create_access": {
                    "type": "boolean"
                },
                "delete_access": {
                    "type": "boolean"
                },
                "export_access": {
                    "type": "boolean"
                },
                "module": {
                    "type": "string"
                },
                "read_access": {
                    "type": "boolean"
                },
                "update_access": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9001",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Login Gateway API",
	Description:      "API Documentation for Login Gateway Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
