name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'   # Trigger only on version tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code at tag
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    
    - name: Make build_runner.sh executable
      run: chmod +x build_runner.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set git user config
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Run build_runner.sh
      run: ./build_runner.sh $GITHUB_REF
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
